remote_theme: "ragupappu/ragupappu.github.io"
plugins:
  - jemoji
pages_list:
  Day1: "/Day1"
  Day2: "/Day2"  
  Day3: "/Day3"
  Day4: "/Day4"
  Day5: "/Day5"
  Day6: "/Day6"
  Day7: "/Day7"  
  Day8: "/Day8"
